()
Prgm
Custom
Title "Simulate"
Item char(34)&char(34)&"→cir:"
Item "s\dc(cir):"
Item "s\tr(cir):"
Item "s\fd(cir):"
Item "s\ac(cir,ω):"
Item "s\er(cir,n1,n2):"
Item "s\th(cir,n1,n2):"
Item "s\ex(cir):"
Title "Elements"
Item "s#,▶n,n▶"
Item "r#,▶n,n▶,Ω"
Item "j#,▶n,n▶,A"
Item "e#,+n,-n,V"
Item "o#,+n,-n,no"
Item "cα,+n,-n,F,vc(0)"
Item "l#,▶n,n▶,H,il(0)"
Item "m#,l#,l#,H"
Title "2 Ports"
Item "t#,n1,n2,N1,N2"
Item "s\port(cir,n1,n2):"
Item "z#,n1,n2"
Item "y#,n1,n2"
Item "h#,n1,n2"
Item "g#,n1,n2"
Item "a#,n1,n2"
Item "b#,n1,n2"
Title "Th"
Item "vth"
Item "ino"
Item "req"
Item "pmax"
Item "vrl"
Item "irl"
Item "prl"
Item "eqcir"
Title "SI"
Item "k"
Item "m"
Item "µ"
Item "n"
Item "p"
Item "f"
Item "true→s\si"
Item "false→s\si"
Title "Tools"
Item "s\only("&char(34)&char(34)&"):"
Item "s\plot()"
Item "s\bode()"
Item "s\s2t("
Item "s\t2s("
Item "s\aa("
Item "s\gain()"
Title "Handy"
Item "1/()"
Item "p(r,r)"
Item "*u(t)"
Item "*δ(t)"
Item "2*π*f→ω:"
Item "approx("
Item "solve( and ,{,})"
Item "cSolve( and ,{,})"
EndCustm
CustmOn
EndPrgm
